---
title: "Programowanie strukturalne - Kolokwium 1 - Zestaw 12"
lang: pl
output:
  word_document: default
  pdf_document: default
---

**Każde zadanie powinno być w oddzielnym pliku. Rozwiązanie umieść 
na swoim indywidualnym repozytorium na Githubie (pojedyncze pliki) lub prześlij jako archiwum zip
poprzez wiadomość prywatną na MS Teams.** 

1. W folderze Debug12 znajduje się projekt z kodem w języku C.
W pliku main.c w niektórych linijkach są komentarze. 
Twoim zadaniem jest wpisanie wartości odpowiednich zmiennych po wykonaniu konkretnej linii kodu.

*Punktacja: 1 pkt za każdą poprawną linijkę, łącznie 8 pkt.*

2. Napisz funkcję, która ma dwa argumenty: dodatnią liczbę całkowitą $n$ oraz dodatnią liczbę wymierną $x$. Funkcja ma zwrócić obliczoną wartość wyrażenia:

$$1+x+\frac{x^2}{2!}+ \frac{x^3}{3!} +\ldots + \frac{x^n}{n!}$$
Stwórz przypadek testowy.

*Punktacja: 9 pkt.*

3. Napisz funkcję, która ma dwa argumenty. Pierwszym argumentem jest wskaźnik na funkcję o jednym argumencie typu `int` zwracającą wartość typu `int`. Drugim argumentem jest wartość typu `int`. Funkcja zwraca resztę z dzielenia przez 5 wartości funkcji otrzymanej w pierwszym argumencie na liczbie całkowitej podanej w drugim argumencie. Stwórz dwa przypadki testowe.

*Punktacja: 10 pkt.*

4. Napisz rekurencyjną funkcję, zwracającą dla otrzymanej w argumencie
nieujemnej liczby całkowitej $n$ wartość elementu o indeksie $n$ ciągu
zdefiniowanego w następujący sposób:

$$ a_n = \begin{cases}
0 & \text{jeśli } n = 0 \\
a_{n - 1} -n & \text{jeśli } a_{n - 1} -n > 0  \\
a_{n - 1} + n & \text{w przeciwnym wypadku.}
\end{cases}$$

Stwórz dwa przypadki testowe.

*Punktacja: 11 pkt.*

5. Napisz funkcję porównująca dwie tablice jednowymiarowe o takich samych rozmiarach o wartościach typu `int`. Funkcja ma zwrócić 1 jeśli sumy elementów nieparzystych z każdej tablic z osobna są sobie równe, oraz ma zwrócić 0 w przeciwnym wypadku.
Stwórz dwa przypadki testowe dla funkcji.

*Punktacja: 12 pkt o ile rozwiązanie korzysta tylko ze wskaźników. 6 pkt za rozwiązanie mieszane lub tylko w notacji tablicowej.*
